<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\GRA.Application\GRA.Application.csproj" />
		<ProjectReference Include="..\GRA.Infra.Persistence\GRA.Infra.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>